# 应用服务 WEB 访问端口
server.port=8080

spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/robot_sso?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
# 指定Mybatis Plus 扫描的mapper文件位置
mybatis-plus.mapper-locations=classpath*:com.wuyunbin/mappers/*.xml


spring.data.redis.host=localhost


jwt.key=e10adc3949ba59abbe56e057f20f883e
jwt.ttl=36000000

wechat.appid=wx084d5d60b374c2a4
wechat.secret=f5207f4068251d589cc12923acd2d759
