version: '3'
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
  mysql:
    container_name: mysql
    image: mysql:8.0.29
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_general_ci
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=demo
      - ./mysql/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "3306:3306"
    privileged: true
    restart: always
  nacos:
    container_name: nacos
    image: zhusaidong/nacos-server-m1:2.0.3
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MODE=standalone
      - PREFER_HOST_MODE=hostname